import { faAndroid, faApple } from "@fortawesome/free-brands-svg-icons";
import {
  faBuilding,
  faCartShopping,
  faGlobe,
  faColumns,
  faSearch,
  faEnvelope,
  faHandHoldingUsd,
  faChartLine,
  faBullhorn,
  faMobile,
  faVideo,
  faMapMarkerAlt,
  faShoppingCart,
  faCog,
  faRetweet,
  faPrint,
  faLaptop,
  faBox,
  faFileAlt,
  faFlag,
  faPalette,
  faChartBar,
  faImage,
  faBook,
  faTshirt,
  faMapSigns,
  faIdCard,
  faShapes,
  faFilm,
  faCamera,
  faFileSignature,
  faMapMarker,
  faBookOpen,
  faSignature,
  faCommentAlt,
  faHandHoldingHeart,
  faSyncAlt,
  faChartPie,
  faDesktop,
  faCogs,
  faMicrophone,
  faTv,
  faGamepad,
  faDraftingCompass,
  faCheckCircle,
  faWrench,
  faShieldAlt,
  faDollarSign,
  faSearch as faSearchAlt,
  faShoppingBag,
  faTools,
  faCalculator,
  faFileInvoice,
  faBlog,
  faInfoCircle,
  faBriefcase,
  faPhone,
  faCreditCard,
  faRightToBracket,
  faUsers,
  faGaugeHigh,
  faMousePointer,
  faShareNodes,
  faFileLines,
  faMobileScreen,
  faSmile,
  faPenNib,
  faIdBadge,
  faLandmark,
  faScroll,
  faCakeCandles,
  faMusic,
  faGraduationCap,
  faSchool,
  faUtensils,
  faWineGlass,
  faDumbbell,
  faChalkboardTeacher,
  faHeart,
  faBaby,
  faHouse,
  faUserTie,
  faLock,
  faGlassCheers,
  faChampagneGlasses,
  faMasksTheater,
  faWater,
  faGlassMartiniAlt,
  faHandshake,
  faChalkboard,
  faMicrophoneLines,
  faAward,
  faBullseye,
  faLightbulb,
  faPuzzlePiece,
  faCalendarCheck,
  faPeopleGroup,
  faChildReaching,
  faRing,
  faPeopleArrows,
} from "@fortawesome/free-solid-svg-icons";

export const eventsLink = [
  {
    category: "Social Events",
    links: [
      {
        path: "/services/events/birthdays",
        title: "Birthdays",
        icon: faCakeCandles,
      },
      {
        path: "/services/events/anniversary-parties",
        title: "Anniversaries",
        icon: faHeart,
      },
      {
        path: "/services/events/baby-showers",
        title: "Baby Showers",
        icon: faBaby,
      },
      {
        path: "/services/events/gender-reveal-parties",
        title: "Gender Reveal Parties",
        icon: faPeopleGroup,
      },
      {
        path: "/services/events/housewarming-parties",
        title: "Housewarming Parties",
        icon: faHouse,
      },
      {
        path: "/services/events/graduation-parties",
        title: "Graduation Parties",
        icon: faGraduationCap,
      },
      {
        path: "/services/events/retirement-parties",
        title: "Retirement Parties",
        icon: faUserTie,
      },
      {
        path: "/services/events/reunion-parties",
        title: "Reunion Parties",
        icon: faUsers,
      },
    ],
  },
  {
    category: "Private Parties",
    links: [
      {
        path: "/services/events/private-parties",
        title: "Private Parties",
        icon: faLock,
      },
      {
        path: "/services/events/bachelor-parties",
        title: "Bachelor Parties",
        icon: faGlassCheers,
      },
      {
        path: "/services/events/bachelorette-parties",
        title: "Bachelorette Parties",
        icon: faChampagneGlasses,
      },
      {
        path: "/services/events/theme-parties",
        title: "Theme Parties",
        icon: faMasksTheater,
      },
      {
        path: "/services/events/pool-parties",
        title: "Pool Parties",
        icon: faWater,
      },
      {
        path: "/services/events/cocktail-parties",
        title: "Cocktail Parties",
        icon: faGlassMartiniAlt,
      },
      {
        path: "/services/events/dinner-parties",
        title: "Dinner Parties",
        icon: faUtensils,
      },
    ],
  },
  {
    category: "Corporate Events",
    links: [
      {
        path: "/services/events/corporate-parties",
        title: "Corporate Parties",
        icon: faBriefcase,
      },
      {
        path: "/services/events/conferences",
        title: "Conferences",
        icon: faUsers,
      },
      {
        path: "/services/events/seminars",
        title: "Seminars",
        icon: faChalkboardTeacher,
      },
      {
        path: "/services/events/product-launches",
        title: "Product Launches",
        icon: faFlag,
      },
      {
        path: "/services/events/award-ceremonies",
        title: "Award Ceremonies",
        icon: faAward,
      },
      {
        path: "/services/events/team-building-events",
        title: "Team Building Events",
        icon: faPeopleArrows,
      },
      {
        path: "/services/events/annual-day",
        title: "Annual Day Events",
        icon: faCalendarCheck,
      },
      {
        path: "/services/events/networking-events",
        title: "Networking Events",
        icon: faShareNodes,
      },
    ],
  },
  {
    category: "Entertainment Events",
    links: [
      {
        path: "/services/events/music-concerts",
        title: "Music Concerts",
        icon: faMusic,
      },
      {
        path: "/services/events/dj-nights",
        title: "DJ Nights",
        icon: faMicrophoneLines,
      },
      {
        path: "/services/events/stand-up-comedy",
        title: "Stand-up Comedy",
        icon: faMicrophone,
      },
      {
        path: "/services/events/fashion-shows",
        title: "Fashion Shows",
        icon: faTshirt,
      },
      {
        path: "/services/events/talent-shows",
        title: "Talent Shows",
        icon: faLightbulb,
      },
      {
        path: "/services/events/cultural-festivals",
        title: "Cultural Events",
        icon: faGlobe,
      },
    ],
  },
  {
    category: "Community & Professional",
    links: [
      {
        path: "/services/events/workshops",
        title: "Workshops",
        icon: faChalkboard,
      },
      {
        path: "/services/events/training-programs",
        title: "Training Programs",
        icon: faGraduationCap,
      },
      {
        path: "/services/events/community-meetups",
        title: "Meetups",
        icon: faUsers,
      },
      {
        path: "/services/events/charity-events",
        title: "Charity Events",
        icon: faHandHoldingHeart,
      },
      {
        path: "/services/events/fundraising-events",
        title: "Fundraising Events",
        icon: faHandHoldingUsd,
      },
      {
        path: "/services/events/art-exhibitions",
        title: "Exhibitions",
        icon: faPalette,
      },
      {
        path: "/services/events/trade-shows",
        title: "Trade Shows",
        icon: faBuilding,
      },
    ],
  },
];

export const digitalMarketingLinks = [
  {
    path: "/services/digital-marketing-company/search-engine-optimization",
    title: "Search Engine Optimization",
    description: "Optimize your website for search engines.",
    icon: faSearch,
  },
  {
    path: "/services/digital-marketing-company/content-marketing",
    title: "Content Marketing",
    description: "Create and distribute valuable content.",
    icon: faFileLines,
  },
  {
    path: "/services/digital-marketing-company/social-media-marketing",
    title: "Social Media Marketing",
    description: "Promote your brand on social platforms.",
    icon: faShareNodes,
  },
  {
    path: "/services/digital-marketing-company/email-marketing",
    title: "Email Marketing",
    description: "Engage your audience with email campaigns.",
    icon: faEnvelope,
  },
  {
    path: "/services/digital-marketing-company/pay-per-click-advertising",
    title: "Pay-Per-Click Advertising",
    description: "Drive traffic with targeted ads.",
    icon: faMousePointer,
  },
  {
    path: "/services/digital-marketing-company/affiliate-marketing",
    title: "Affiliate Marketing",
    description: "Boost sales through affiliate programs.",
    icon: faHandHoldingUsd,
  },
  {
    path: "/services/digital-marketing-company/analytics-and-data-analysis",
    title: "Analytics and Data Analysis",
    description: "Gain insights from data for better strategies.",
    icon: faChartLine,
  },
  {
    path: "/services/digital-marketing-company/conversion-rate-optimization",
    title: "Conversion Rate Optimization",
    description: "Improve website conversion rates.",
    icon: faGaugeHigh,
  },
  {
    path: "/services/digital-marketing-company/mobile-marketing",
    title: "Mobile Marketing",
    description: "Target users on mobile devices.",
    icon: faMobile,
  },
  {
    path: "/services/digital-marketing-company/video-marketing",
    title: "Video Marketing",
    description: "Use videos for effective marketing.",
    icon: faVideo,
  },
  {
    path: "/services/digital-marketing-company/local-seo-and-marketing",
    title: "Local SEO and Marketing",
    description: "Enhance local online visibility.",
    icon: faMapMarkerAlt,
  },
  {
    path: "/services/digital-marketing-company/ecommerce-marketing",
    title: "Ecommerce Marketing",
    description: "Promote products in online stores.",
    icon: faShoppingCart,
  },
  {
    path: "/services/digital-marketing-company/marketing-automation",
    title: "Marketing Automation",
    description: "Automate marketing tasks for efficiency.",
    icon: faCog,
  },
  {
    path: "/services/digital-marketing-company/remarketing-retargeting",
    title: "Remarketing and Retargeting",
    description: "Re-engage potential customers.",
    icon: faRetweet,
  },
  {
    path: "/services/digital-marketing-company/influencer-marketing",
    title: "Influencer Marketing",
    description: "Collaborate with influencers for promotion.",
    icon: faUsers,
  },
];

export const multimediaLinks = [
  {
    path: "/services/multimedia-company/logo-design",
    title: "Logo Design",
    description: "Create a unique logo for your brand.",
    icon: faPenNib,
  },
  {
    path: "/services/multimedia-company/brand-identity-design",
    title: "Brand Identity Design",
    description: "Build a strong brand identity.",
    icon: faPalette,
  },
  {
    path: "/services/multimedia-company/print-design",
    title: "Print Design",
    description: "Design materials for print.",
    icon: faPrint,
  },
  {
    path: "/services/multimedia-company/web-design",
    title: "Web Design",
    description: "Create stunning websites.",
    icon: faLaptop,
  },
  {
    path: "/services/multimedia-company/user-interface-design",
    title: "User Interface Design",
    description: "Design user-friendly interfaces.",
    icon: faDesktop,
  },
  {
    path: "/services/multimedia-company/user-experience-design",
    title: "User Experience Design",
    description: "Enhance user satisfaction.",
    icon: faSmile,
  },
  {
    path: "/services/multimedia-company/packaging-design",
    title: "Packaging Design",
    description: "Create attractive packaging.",
    icon: faBox,
  },
  {
    path: "/services/multimedia-company/poster-and-flyer-design",
    title: "Poster and Flyer Design",
    description: "Design promotional materials.",
    icon: faFileAlt,
  },
  {
    path: "/services/multimedia-company/brochure-design",
    title: "Brochure Design",
    description: "Design informative brochures.",
    icon: faFileAlt,
  },
  {
    path: "/services/multimedia-company/banner-design",
    title: "Banner Design",
    description: "Design eye-catching banners.",
    icon: faFlag,
  },
  {
    path: "/services/multimedia-company/illustration-services",
    title: "Illustration Services",
    description: "Get custom illustrations.",
    icon: faPalette,
  },
  {
    path: "/services/multimedia-company/infographic-design",
    title: "Infographic Design",
    description: "Create informative infographics.",
    icon: faChartBar,
  },
  {
    path: "/services/multimedia-company/social-media-graphics",
    title: "Social Media Graphics",
    description: "Design graphics for social media.",
    icon: faImage,
  },
  {
    path: "/services/multimedia-company/ebook-and-print-book-cover-design",
    title: "eBook and Print Book Cover Design",
    description: "Design book covers.",
    icon: faBook,
  },
  {
    path: "/services/multimedia-company/t-shirt-and-merchandise-design",
    title: "T-shirt and Merchandise Design",
    description: "Design for apparel and merchandise.",
    icon: faTshirt,
  },
  {
    path: "/services/multimedia-company/signage-and-billboard-design",
    title: "Signage and Billboard Design",
    description: "Create signage and billboards.",
    icon: faMapSigns,
  },
  {
    path: "/services/multimedia-company/business-card-and-stationery-design",
    title: "Business Card and Stationery Design",
    description: "Design business cards and stationery.",
    icon: faIdCard,
  },
  {
    path: "/services/multimedia-company/rendering-and-visualization",
    title: "Rendering and Visualization",
    description: "Create 3D renderings and visualizations.",
    icon: faShapes,
  },
  {
    path: "/services/multimedia-company/motion-graphics-and-animation",
    title: "Motion Graphics and Animation",
    description: "Design motion graphics and animations.",
    icon: faFilm,
  },
  {
    path: "/services/multimedia-company/photo-editing-and-retouching",
    title: "Photo Editing and Retouching",
    description: "Edit and retouch photos.",
    icon: faCamera,
  },
];

export const brandingLinks = [
  {
    path: "/services/branding-comapny/brand-identity-design-exclusive",
    title: "Brand Identity Design Exclusive",
    description: "Exclusive brand identity design services.",
    icon: faIdBadge,
  },
  {
    path: "/services/branding-comapny/brand-logo-design",
    title: "Brand Logo Design",
    description: "Design a unique logo for your brand.",
    icon: faPenNib,
  },
  {
    path: "/services/branding-comapny/brand-guidelines",
    title: "Brand Guidelines",
    description: "Create brand guidelines for consistency.",
    icon: faFileSignature,
  },
  {
    path: "/services/branding-comapny/brand-positioning",
    title: "Brand Positioning",
    description: "Strategically position your brand.",
    icon: faMapMarker,
  },
  {
    path: "/services/branding-comapny/brand-storytelling",
    title: "Brand Storytelling",
    description: "Craft compelling brand stories.",
    icon: faBookOpen,
  },
  {
    path: "/services/branding-comapny/brand-naming",
    title: "Brand Naming",
    description: "Find the perfect name for your brand.",
    icon: faSignature,
  },
  {
    path: "/services/branding-comapny/visual-identity-design",
    title: "Visual Identity Design",
    description: "Design a strong visual identity.",
    icon: faPalette,
  },
  {
    path: "/services/branding-comapny/brand-messaging",
    title: "Brand Messaging",
    description: "Create effective brand messaging.",
    icon: faCommentAlt,
  },
  {
    path: "/services/branding-comapny/brand-experience-design",
    title: "Brand Experience Design",
    description: "Enhance the brand experience.",
    icon: faHandHoldingHeart,
  },
  {
    path: "/services/branding-comapny/brand-awareness-campaigns",
    title: "Brand Awareness Campaigns",
    description: "Run brand awareness campaigns.",
    icon: faBullhorn,
  },
  {
    path: "/services/branding-comapny/rebranding-services",
    title: "Rebranding Services",
    description: "Rebrand your business effectively.",
    icon: faSyncAlt,
  },
  {
    path: "/services/branding-comapny/brand-research-and-analysis",
    title: "Brand Research and Analysis",
    description: "Conduct brand research and analysis.",
    icon: faChartPie,
  },
  {
    path: "/services/branding-comapny/brand-tracking-and-performance-evaluation",
    title: "Brand Tracking and Performance Evaluation",
    description: "Track and evaluate brand performance.",
    icon: faChartLine,
  },
];

export const advertisingLinks = [
  {
    path: "/services/advertising-company/display-advertising",
    title: "Display Advertising",
    description: "Effective display advertising solutions.",
    icon: faDesktop,
  },
  {
    path: "/services/advertising-company/video-advertising",
    title: "Video Advertising",
    description: "Engage with video advertising campaigns.",
    icon: faVideo,
  },
  {
    path: "/services/advertising-company/native-advertising",
    title: "Native Advertising",
    description: "Discover native advertising strategies.",
    icon: faScroll,
  },
  {
    path: "/services/advertising-company/programmatic-advertising",
    title: "Programmatic Advertising",
    description: "Efficient programmatic advertising.",
    icon: faCogs,
  },
  {
    path: "/services/advertising-company/outdoor-advertising",
    title: "Outdoor Advertising",
    description: "Outdoor advertising solutions.",
    icon: faLandmark,
  },
  {
    path: "/services/advertising-company/print-advertising",
    title: "Print Advertising",
    description: "Effective print advertising services.",
    icon: faFileAlt,
  },
  {
    path: "/services/advertising-company/radio-advertising",
    title: "Radio Advertising",
    description: "Reach audiences through radio ads.",
    icon: faMicrophone,
  },
  {
    path: "/services/advertising-company/tv-advertising",
    title: "TV Advertising",
    description: "Impactful TV advertising campaigns.",
    icon: faTv,
  },
  {
    path: "/services/advertising-company/ingame-advertising",
    title: "In-Game Advertising",
    description: "Advertise within video games.",
    icon: faGamepad,
  },
  {
    path: "/services/advertising-company/theater-advertising",
    title: "Theater Advertising",
    description: "Promote in theaters and cinemas.",
    icon: faFilm,
  },
];

export const moreLinks = [
  {
    path: "/blogs",
    title: "Blogs",
    description: "Read our latest insights and articles.",
    icon: faBlog,
  },
  {
    path: "/services",
    title: "Services",
    description: "Looking for a Job? Join our team.",
    icon: faTools,
  },
  {
    path: "/Careers",
    title: "Careers",
    description: "Looking for a Job? Join our team.",
    icon: faBriefcase,
  },

  {
    path: "/auth/login",
    title: "Login",
    description: "If you are a customer or existing user, please login.",
    icon: faRightToBracket,
  },
];
